import "./globals.css";
import {Inter} from "next/font/google";
import {cn} from "~/lib/utils";
import type {Metadata} from "next";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const style = cn([inter.className, "min-h-screen min-w-screen"]);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={style}>{children}</body>
    </html>
  );
}
